services:
  mongodb:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  api:
    build: .
    container_name: nest-api
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/fps
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
